import { sql } from "drizzle-orm";
import {
	boolean,
	index,
	pgTable,
	text,
	timestamp,
	uuid,
} from "drizzle-orm/pg-core";

/**
 * Drizzle schema for better-auth's tables, generated by `@better-auth/cli
 * generate` (core + emailOTP + bearer, v1.6.14) and passed to `drizzleAdapter`.
 *
 * Lives in the runner for now. Phase 3 relocates it into `@repo/database` as
 * part of the full Drizzle schema for all 12 tables — that move requires giving
 * `@repo/database` a real build (it currently ships raw `.ts` for types-only
 * consumption), which ripples to the web build, so it's sequenced with Phase 3
 * rather than pulled in here. See the migration doc.
 *
 * `users` is the EXISTING `public.users` table (extended in migration
 * 20260605120000); sessions/accounts/verifications are created in 20260605130000.
 *
 * Deviation from the raw generator output: `name` is nullable here to match the
 * real column (existing rows predate the email/name backfill and may be null);
 * better-auth marks it notNull by default.
 */
export const users = pgTable("users", {
	id: uuid("id")
		.default(sql`pg_catalog.gen_random_uuid()`)
		.primaryKey(),
	name: text("name"),
	email: text("email").notNull().unique(),
	emailVerified: boolean("email_verified").default(false).notNull(),
	image: text("image"),
	createdAt: timestamp("created_at").defaultNow().notNull(),
	updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export const sessions = pgTable(
	"sessions",
	{
		id: uuid("id")
			.default(sql`pg_catalog.gen_random_uuid()`)
			.primaryKey(),
		expiresAt: timestamp("expires_at").notNull(),
		token: text("token").notNull().unique(),
		createdAt: timestamp("created_at").defaultNow().notNull(),
		updatedAt: timestamp("updated_at").defaultNow().notNull(),
		ipAddress: text("ip_address"),
		userAgent: text("user_agent"),
		userId: uuid("user_id")
			.notNull()
			.references(() => users.id, { onDelete: "cascade" }),
	},
	(table) => [index("sessions_user_id_idx").on(table.userId)],
);

export const accounts = pgTable(
	"accounts",
	{
		id: uuid("id")
			.default(sql`pg_catalog.gen_random_uuid()`)
			.primaryKey(),
		accountId: text("account_id").notNull(),
		providerId: text("provider_id").notNull(),
		userId: uuid("user_id")
			.notNull()
			.references(() => users.id, { onDelete: "cascade" }),
		accessToken: text("access_token"),
		refreshToken: text("refresh_token"),
		idToken: text("id_token"),
		accessTokenExpiresAt: timestamp("access_token_expires_at"),
		refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
		scope: text("scope"),
		password: text("password"),
		createdAt: timestamp("created_at").defaultNow().notNull(),
		updatedAt: timestamp("updated_at").defaultNow().notNull(),
	},
	(table) => [index("accounts_user_id_idx").on(table.userId)],
);

export const verifications = pgTable(
	"verifications",
	{
		id: uuid("id")
			.default(sql`pg_catalog.gen_random_uuid()`)
			.primaryKey(),
		identifier: text("identifier").notNull(),
		value: text("value").notNull(),
		expiresAt: timestamp("expires_at").notNull(),
		createdAt: timestamp("created_at").defaultNow().notNull(),
		updatedAt: timestamp("updated_at").defaultNow().notNull(),
	},
	(table) => [index("verifications_identifier_idx").on(table.identifier)],
);

/** Combined object passed to better-auth's `drizzleAdapter({ schema })`. */
export const authSchema = { users, sessions, accounts, verifications };
